E_SUCCESS = 0
E_FAIL = 1


# Section Auth
E_AUTH = 10000
E_AUTH_TOKEN_CHECK_FAIL = E_AUTH + 1
E_AUTH_TOKEN_TYPE_INVALID = E_AUTH + 2
E_AUTH_TOKEN_TIMEOUT = E_AUTH + 3
E_AUTH_USERPASSWD_INVALID = E_AUTH + 4


# Section User
E_USER = 20000
E_USER_INACTIVE = E_USER + 1
E_USER_MISS_PERM = E_USER + 2

E_USER_R = E_USER + 1000
E_USER_R_NOTFOUND = E_USER_R + 1

E_USER_C = E_USER + 2000
E_USER_C_USER_EXIST = E_USER_C + 1

E_USER_U = E_USER + 3000
E_USER_U_PASSWORD_NOTMATCH = E_USER_U + 1
E_USER_U_INFO_INTERNAL = E_USER_U + 2

E_USER_D = E_USER + 4000
